version: "3"

services:
    service_a:
        container_name: service_a
        build: ./service_a
        ports:
            - 4001:5000

    service_b:
        container_name: service_b
        build: ./service_b
        ports:
            - 4000:4000
        depends_on:
            - service_a
